name: pipePython

on: 
  push:
    branches: [main]


jobs:
  teste_soma:
    runs-on: ubuntu-latest
    steps: 
    - name: pull repositorio
      uses: actions/checkout@v3
    - name: configurar dependencias
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: instalar dependências
      run: pip install pytest

    - name: instalar dependências
      run: pip install pytest
      
